//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindTheGap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int eventId { get; set; }
        public string userId { get; set; }
        public Nullable<int> interestId { get; set; }
        public string summary { get; set; }
        public string description { get; set; }
        public string location { get; set; }
        public string colorId { get; set; }
        public System.DateTime starttime { get; set; }
        public System.DateTime endtime { get; set; }
        public string recurrence { get; set; }
        public Nullable<bool> reminders { get; set; }
        public bool completed { get; set; }
    
        public virtual Interest Interest { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
