//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindTheGap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gap
    {
        public Nullable<System.DateTime> GapStart { get; set; }
        public Nullable<System.DateTime> GapEnd { get; set; }
        public int GapId { get; set; }
    }
}
