//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindTheGap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progress
    {
        public int progressId { get; set; }
        public string userId { get; set; }
        public int interestId { get; set; }
        public double total { get; set; }
        public System.DateTime endDate { get; set; }
    
        public virtual Interest Interest { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
